
import json
import os

en_data_1 = {
    1: {"poem": "The Heavenly Gate posts the list, destined to win the prize. Horses neigh in the fragrant grass, deer call in the high autumn.", "explain": "Great luck. Career, wealth, health, and marriage are all smooth."},
    2: {"poem": "The Earth has spirits, very powerful and majestic. Revitalizing the nation, assisting the country, honoring the lord, protecting the people.", "explain": "Divine protection lot. Follow the rules. You will have noble help in your career. Good marriage and health."},
    3: {"poem": "The flowers of Chang'an are unreachable, the horse hooves are fast in the spring breeze. Whip early, suddenly colorful.", "explain": "Be vigilant, do not aim too high. Current situation is not ideal."},
    4: {"poem": "Spring flowers are charming, but cannot withstand rain and wind. Autumn chrysanthemums are fragrant, standing proud against frost and snow.", "explain": "A lot of caution. Things are not going smoothly. Be down-to-earth and there may be hope."},
    5: {"poem": "Spring thunder shakes, summer wind blows. The sleeping dragon rises, the fierce tiger is startled. Wind and clouds meet, saving the people.", "explain": "Misfortune turns to fortune. Rain after a drought. But marriage may have waves. Travel is not suitable."},
    6: {"poem": "Not mysterious nor profound, not shallow nor deep. A wonderful path, search with intention.", "explain": "Do not be impatient. Search with intention, and you will get what you want."},
    7: {"poem": "You must realize, do not doubt. There is a flat road, ride as you please. Change with the times, everything is suitable.", "explain": "Be alert and adaptable, then you can handle everything smoothly."},
    8: {"poem": "The tiger loves the high mountain with a hidden motive, people are still suspicious. The wild geese call, yellow flowers bloom. At this time fame reaches the capital.", "explain": "No one recognizes you now, but you will be praised later. Those with talent but no opportunity will succeed later."},
    9: {"poem": "Noble guests meet as expected. The phoenix comes to the withered tree in the courtyard. Seek long-term goals, ignore gossip.", "explain": "You will meet noble helpers. Unmarried men will find good partners. Businessmen should have their own opinions to make profits."},
    10: {"poem": "The lone wild goose stands out from the flock, flying high with tangled wings. Progress north, good news is heard. Morning clouds and evening rain mixed together.", "explain": "Outstanding talent but restricted. Going North is good. You will have good encounters."},
    11: {"poem": "No trace, no track, hard to find far or near. Wind and waves rise on flat ground, smiles turn to tears.", "explain": "Everything is unfavorable."},
    12: {"poem": "Spirit is gloomy, mind is leisurely. Put away the line, do not lower the hook.", "explain": "Pause everything for now to avoid mistakes and regret."},
    13: {"poem": "Proud when meeting a woman, destiny has a connection. Fame and profit are hopeful, reunion in three to five months.", "explain": "Auspicous. Pay attention to months/days with 3 or 5. Good luck or happy events."},
    14: {"poem": "Wind and waves rise in the boiling cauldron, a lone boat wants to cross the river. Clumsiness hidden in skill, human affairs turn to waste.", "explain": "Inauspicious. Beware of attracting too much attention. Arguments in marriage or family."},
    15: {"poem": "Intention is in leisure, news has not come. Old friends wander a thousand miles away. The goose foot brings news, a plum blossom brings back spring.", "explain": "Expectations will be met, but you must wait a while."},
    16: {"poem": "Hearts are in harmony, things are known together. Good deeds outside the door, interactions have an end.", "explain": "Those who are separated will reunite."},
    17: {"poem": "Want to go but stop, wandering endlessly. Hiding jade and carrying pearls, a heart a thousand miles away.", "explain": "Hesitating but ready to go. Make up your mind to achieve great things."},
    18: {"poem": "Heart is sad, mouth is chattering. One thought, one worry. Said to stop but never stops.", "explain": "Unfavorable. Outcome is unlikely to be hopeful."},
    19: {"poem": "Not far not near, seems easy seems hard. An ordinary matter, watching from the clouds with a smile.", "explain": "Average. Treat success and failure lightly."},
    20: {"poem": "Peach and plum wither in spring wind, flying west then east. No mood at home, boat in the waves.", "explain": "Planting at the wrong time. Drifting direction. Travel is not smooth. Family has waves."},
    21: {"poem": "One water further than another, one mountain after another. Where water ends and mountains end, fame and profit are not difficult.", "explain": "Success comes after great effort."},
    22: {"poem": "Things support each other, halfway through. Overturning can be avoided, no wind and waves.", "explain": "Currently not smooth, but no risk."},
    23: {"poem": "Joy, joy, joy. Spring wind gives birth to peach and plum. No need to worry, the moon shines on people a thousand miles away.", "explain": "Good news arrives. Old friends are safe. Health recovers. Marriage is expected."},
    24: {"poem": "Diligent in mind, sad in heart. To be safe, watch your coming and going.", "explain": "Be cautious in words and deeds to be safe."},
    25: {"poem": "See or not see, beware of people behind your back. Meet or not meet, no proof in the end.", "explain": "Beware of backstabbing from the West. No sign of what you asked."},
    26: {"poem": "A season of peach and plum, a season of spring. Who knew the weather was new at first. Seeking livelihood by the water and forest, seeing the mountains pleases the heart.", "explain": "New job is possible. Agriculture/forestry/fishing is good. Sick should change doctor and rest in nature."},
    27: {"poem": "Do not blame my wrong view, nature becomes a disease. Biased and unreasonable, a real person is not a demon.", "explain": "Do not be stubborn. Cultivate your character."},
    28: {"poem": "Wealth and horses intersect, time for a man to succeed. Prepare for the journey early, return with glory and joy.", "explain": "Auspicous. Especially suitable for official career."},
    29: {"poem": "Settled the matter in the heart, fate from three lives. Fragrance of cassia for ten miles, stepping into the sky.", "explain": "Great luck. Especially for marriage. Autumn (Cassia season) is suitable."},
    30: {"poem": "Climbing high and turning white-headed, what is the use in the end? Better to take this spirit, and buy some genuine energy.", "explain": "Those seeking power should turn back. Be an upright person. Otherwise, it won't end well."},
    31: {"poem": "Parting is not easy. Walking together, no delay. Start the journey early, avoid disappointment.", "explain": "Average. Start business with a partner."},
    32: {"poem": "Extreme joy brings sorrow. Xun and Dui clearly show good and bad. Cannot shine in the end, gloomy. Sunset on the western hill reflects.", "explain": "Ominous."},
    33: {"poem": "Experienced three or five waves, who knows it is calm and windless. Must teach the bright road to blue clouds, action and inaction require no effort.", "explain": "Average."},
    34: {"poem": "Missing moon is full again, withered branch is fresh again. A flat road, looking up at the blue sky.", "explain": "Auspicous."},
    35: {"poem": "Hard to travel, hard to travel. Today I know it is hard to travel. Why worry about the vast future, use strength to cross this beach today.", "explain": "Always smooth, suddenly dangerous. But you will pass."},
    36: {"poem": "Spring scenery is bright, spring color is new. Spring meaning grows by the water. Spring is infinitely good, go to the banquet.", "explain": "Career developed. Health good. Open-minded. Wide social circle."},
    37: {"poem": "Ten thousand horses return to the origin, a thousand apes bow to the cave. Tigers submit and dragons surrender, high Dao and heavy virtue.", "explain": "Influence people with virtue."},
    38: {"poem": "Yellow oriole reports in the forest, spring colors are bright. Raise the whip quickly, speed up the journey.", "explain": "Best time to do anything right now."},
    39: {"poem": "Freely give panacea, save thousands of people. Reach the other shore in the end, join the immortals.", "explain": "Do good deeds. Doctors will be famous, teachers will be famous."},
    40: {"poem": "A belt of water, clear and blue. Boat stays on the river, moon in the sky center. Steady steps in it, mysterious and not idle. Wrong person harms self, almost lost life.", "explain": "Blessing in disguise. Things are not smooth, but no big mistake yet. Can retreat safely."},
    41: {"poem": "Peach and plum bloom, spring light is fresh. Remember the beautiful day. Follow your heart, everything is suitable. No need to doubt and disturb the gods.", "explain": "Auspicous. Everything is destined to be smooth. Doubt will waste God's favor."},
    42: {"poem": "Hidden in the obvious, subtle in the obvious. There is a mystery in it. If you see through it, go straight to the celestial ladder.", "explain": "Situation is stuck. Depends on if you can see the mystery from clues."},
    43: {"poem": "No way up, in the front. Turn back and realize, gather the reins. Thousands of roads are always there, search for yourself.", "explain": "Wrong direction. Change course and find a feasible path."},
    44: {"poem": "Looking around, no way. The path to Peach Blossom Source is open. Cultivate to the right result, long life like a pine.", "explain": "Average. Luck is blocked, but there is a ray of hope. Hard work will lead to success."},
    45: {"poem": "No need to be busy, no need to panic. There is a place to stop. Place of drums and bells, see the gate of the Three Treasures.", "explain": "Be calm, there is a place for you. Do charity, good luck will come."},
    46: {"poem": "Running around all life, always empty. When impermanence comes, everything stops. Turn back early.", "explain": "Fighting for fame and profit ends in nothing. Turn back to the shore."},
    47: {"poem": "True, true, true, people do not know. True, true, true, gods are effective. Return to the origin, that is the essence.", "explain": "Blinded by false appearances, went astray. Recognize the truth, return to the right path."},
    48: {"poem": "Walked to the end of the world, experienced wind and frost. Better to ask someone for three days, gradually look back.", "explain": "Rash progress wastes effort. Ask the wise."},
    49: {"poem": "Deep sickness, cannot see the sky. Thunder shakes, body becomes healthy and light.", "explain": "Long illness will meet a good doctor. Business will find good talent."},
    50: {"poem": "Wealth and horses are busy, official salary has a fixed place. Pig, sheep, cow, dog, go and decide for themselves.", "explain": "Let nature take its course."},
    51: {"poem": "Empty, empty, empty, success in emptiness. Peach ripens in a thousand years, not afraid of the fifth watch wind.", "explain": "Late success. Unlucky for wealth. Good for winning lawsuits after delay."},
    52: {"poem": "Frowns released, smiles open. Autumn moon hangs on the high tower, people come from a thousand miles.", "explain": "Auspicous. Mood improves. Environment gets better. Reunion expected."},
    53: {"poem": "Must exert effort, do not travel far. Long pole fishes in the toad cave, straight to the clouds to get the giant turtle.", "explain": "Caution. Go all out. Don't play around. Wishes will come true when luck comes."},
    54: {"poem": "No trace, no track, hard to find far or near. Boat in a dry sea, wasted effort.", "explain": "Hard to succeed."},
    55: {"poem": "Fine rain is misty and wet, the road by the river is blocked. News is far away, rely on the east wind.", "explain": "Bad luck. Hard to achieve anything. Rely on the only ray of hope."},
    56: {"poem": "Smoke rises on flat ground, currently unstable. Seek marriage in high places.", "explain": "Nothing can be achieved here and now. Seek marriage from prominent families. Career has twists."},
    57: {"poem": "Uprightness should be kept, rash action brings disaster. Profit and fame achieved, leaves fall and flowers bloom.", "explain": "Stick to your position. Be upright."},
    58: {"poem": "Gentleman rises, villain blocks. Suffering from war and separation. Meet a good person in front. Letter on horse/cow, person in Chu. Plan carefully.", "explain": "Twists and turns. Help and destruction coexist. No geographical advantage. Plan carefully."},
    59: {"poem": "Disordered and messy, sobbing alone behind the door. Looking at the lamp, sitting with me at dusk.", "explain": "Wait for the right time. Don't force it. Wife may have discord."},
    60: {"poem": "Red face is beautiful, do not worry. Person in the cart, boat in the water.", "explain": "Beware of lust. Do not have extravagant hopes."},
    61: {"poem": "Bridge is broken, road blocked. Board the boat and row, encounter wild wind again.", "explain": "Very ominous. Be careful in everything."},
    62: {"poem": "Moon in deep pool, image in mirror. All in vain, waiting for news.", "explain": "Moon in water, flower in mirror. All effort in vain."},
    63: {"poem": "Lake and sea meaning is leisurely, fishing hook in the misty waves. If dragon and rabbit are met, fame and profit are complete.", "explain": "Be broad-minded. Fame and profit will come. (Note Dragon/Rabbit years or people)."},
    64: {"poem": "Things are not firm, people break the bridge. Reorganize, slow down the high heart.", "explain": "Start over. Be practical, maybe success."},
    65: {"poem": "Easy to enter, hard to exit. Languid again and again. Mixed feelings are unbearable.", "explain": "Easy to invite a god, hard to send him away."},
    66: {"poem": "Events delay, will is fast, and repetitive. Wait until winter, flowers fade and fruits ripen.", "explain": "Time is not ripe. Hard to succeed by yourself. Women waste youth."},
    67: {"poem": "Ride a horse forward, what you seek is auspicious. Harmonious at any time, missing moon brightens again.", "explain": "Go forward bravely. Even if there were mistakes, you can revitalize."},
    68: {"poem": "Boat leaves the old ferry, moon leaves the clouds. People leave Tongguan to ask for the way. Just go forward to seek residence, why hesitate.", "explain": "Good for travel/outside. Difficulties solved. Smooth path ahead."},
    69: {"poem": "Insufficient, insufficient, hard to express heart's song. Rain passes over wild pond, moon like a hook. Dream broken in Handan, eyebrows frowning.", "explain": "Be content. Adapt. Otherwise dreams won't come true. Women should abandon vanity."},
    70: {"poem": "Beauty has worth, worth has beauty. Beginning has end, end has beginning.", "explain": "Pursue truth, goodness, and beauty. Be consistent."},
    71: {"poem": "Lakes and seas are vast, lone boat on the waves. The person has not crossed, setting sun on the mountain tower.", "explain": "Things are vague. Situation not open. Depressed mood."},
    72: {"poem": "Deep doors must be locked, beware of people in the dark. Do not say there are no outside matters, even good things encounter disasters.", "explain": "Be careful even if nothing happens. Guard against theft. Be cautious in speech."},
    73: {"poem": "River and sea are vast, hook in the misty waves. Six turtles caught in a row, singing and laughing in midstream.", "explain": "Great luck. Business/Entrepreneurship hopeful. Success in a row. Number 6 is lucky."},
    74: {"poem": "Want to cross but not crossed, want to force but forced. Heart is uncertain, one cart two heads.", "explain": "Indecisive. Against logic. Stuck. Things are in a stalemate."},
    75: {"poem": "One gain one worry, retreat to advance. Road leads to the main way, heart is naturally at peace.", "explain": "Don't be arrogant in success, don't be discouraged in failure. Stay on right path."},
    76: {"poem": "Hard, hard, hard, suddenly waves rise on flat ground. Easy, easy, easy, talking and laughing, finally there is hope.", "explain": "Bad luck: disaster from sky. Good luck: everything handy."},
    77: {"poem": "Heart has excess, strength is insufficient. Rely on spring breeze, one song one tune.", "explain": "Cannot do it alone. External help will come. Result is satisfactory."},
    78: {"poem": "Body uneasy, heart uneasy. Movement and stillness two or three times. Sighing all morning.", "explain": "Health: exercise. Career: crisis. Marriage: weary. Need effort."},
    79: {"poem": "Matter finished, object not finished. People round, object not round. To know the true news, sun shadow on the jade.", "explain": "People/Matters resolved. Material things not. Financial disputes or lawsuits likely."},
    80: {"poem": "Wood grows towards spring sun, three shades cover the root. Woodcutter does not know, cuts it for firewood.", "explain": "Do not waste things. Misunderstanding the value and discarding it is a pity."},
    81: {"poem": "One moon missing, one mirror missing. Not reunited, nothing to say.", "explain": "Inauspicious. Incomplete. No turning point."},
    82: {"poem": "Chariots and horses arrive, flags hidden, moon is clear. Pacify and punish rebels, eternal future.", "explain": "Military: Great luck. Business: Great success. Exam: High pass."},
    83: {"poem": "Where do I stay? Where do I stay? Fame recorded in Haidong and Hebei. A ray of divine light, straight to heaven.", "explain": "Choose direction. Learn from predecessors. Like divine help."},
    84: {"poem": "Gold scales in hand, guard against leaving. If discussing socializing, keep mouth shut.", "explain": "Gold scales = Money. Be silent. Beware of being cheated by friends borrowing money."},
    85: {"poem": "Tilt a cup, spread frowning eyebrows. Heaven and earth join, good to think and do.", "explain": "Sorrows dissolved in wine. Husband and wife discord should be resolved quickly."},
    86: {"poem": "Wild ghost draws bow to shoot master, secret arrow scares the soul. Suddenly red sun sinks in river and sea, hard to break the mystery in the air.", "explain": "If a leader, beware of bullying subordinates, resulting in fatal revenge."},
    87: {"poem": "Lucky star shines, auspicious star arrives. Blue sky has sun, seeing innocence. Dragon flies down to the bright court.", "explain": "Auspicious. Blessed by virtue."},
    88: {"poem": "Fishing alone in cold pool, interest fades halfway. Water cold fish don't bite, return with only moonlight.", "explain": "Ominous. Bad environment. Wishes not met. Obstacles."},
    89: {"poem": "Not unified, laboring mind and strength. Noble person nearby, should borrow strength.", "explain": "Opinions divided. Messy. Must borrow strength from powerful people."},
    90: {"poem": "Clouds gone, moon in the center. Brilliance everywhere. Road meets smooth water, thousand miles fast as wind.", "explain": "Turning point. Good luck. Everything auspicious."},
    91: {"poem": "Swords and halberds in the forest, thieves will invade. Defeated and captured, nobility for descendants.", "explain": "Fierce competition. Anticipate enemy. Win and manage results well."},
    92: {"poem": "Bank wide water deep boat easily falls. Road far mountain dangerous hard to walk. Snake travel has a day of passage, moon in sky exceptionally bright.", "explain": "Plan broadly. Think long term. Success in the end."},
    93: {"poem": "Intend to move but cannot move yet, beware of trouble in happy places. If guided by a woman/hidden person, change from fish to dragon out of the abyss.", "explain": "Don't get dizzy with joy. Beware of trouble in happiness."},
    94: {"poem": "One person goes, one person enters. Breeze and bright moon guess each other. Get gold scales off the fishing platform.", "explain": "Suspicion before cooperation success. Manners remain. Marriage: worry about no heir, then get a daughter."},
    95: {"poem": "Joy not steady, sorrow already encountered. Heavy rain and wild wind blow old trees, everyone says it's not firm.", "explain": "Joy and sorrow are impermanent. Sorrow is often severe."},
    96: {"poem": "Can entrust life of a hundred miles, can entrust an orphan of six feet. Meeting Zhong Qi, do not delay. Laughing, gathering in foreign land, everyone happy and healthy.", "explain": "Meet a soulmate. Best friend. Life partner."},
    97: {"poem": "Report to Shanglin, spring colors are bright. Raise whip quickly, start journey on horse.", "explain": "Prosperous and smooth. Luck turns good."},
    98: {"poem": "Rat enters earthen hole, safest place. Not seen in the day, patrolling in quiet night.", "explain": "Everyone has their place and time. Choosing otherwise is unfavorable."},
    99: {"poem": "Strike up lifelong ambition, go to Southwest to travel. Waist wrapped with ten thousand strings of cash, ride a crane to Yangzhou.", "explain": "Achieved fame and success. Or, change career to what you like if wealthy."},
    100: {"poem": "Joy, joy, joy, finally guard against denial. Get the pearl under the dragon's chin, suddenly lose it, still in the water.", "explain": "Beware of extreme joy turning to sorrow."},
    101: {"poem": "Country has wise men, court has no flatterers. Weapons not used, enjoy peace forever.", "explain": "Peaceful times. Family harmony."},
    102: {"poem": "Tai comes after Pi extremes, do not worry about things. But must cultivate original blessing, do good deeds, act conveniently. One point of spiritual elixir alone gets the truth.", "explain": "Cultivate character. Do good deeds."},
    103: {"poem": "People enjoy their work, officials are clear. World of Yongxi seen again today. Tell everyone eternal great karma, rely on this to hope for wise ruler.", "explain": "Leaders should ensure subordinates are in place and honest."},
    104: {"poem": "Safe as Mount Tai, steady as a rock. Go forward boldly, open inside and straight outside.", "explain": "Great luck."},
    105: {"poem": "Moon has cinnabar cassia, people cannot reach it. Cloud ladder grows under feet, good place to land now.", "explain": "Ambitious goal hard to reach. With help, success is possible."},
    106: {"poem": "A lone goose in the sky, crying about leaving the flock. Ask who knows you, how many people now.", "explain": "Loneliness of the frustrated. Adjust attitude."},
    107: {"poem": "Red leaves have no color, withered by one night of wind. Neighbor's chicken wakes noon dream, heart matters all become empty.", "explain": "Good luck passes quickly. Ideal blocked. Hard to achieve."},
    108: {"poem": "Matters like hemp, reasons mostly wrong. Sun hidden in clouds, delay in vain.", "explain": "Chaotic situation. Bad luck. Wasted time. Nothing achieved."},
    109: {"poem": "Do not go on old tracks, willing to drive new car. East, West, South, North, steady steps on thoroughfare.", "explain": "Do not repeat mistakes. Change course."},
    110: {"poem": "Night dream startled by rat, wake up see no one. Sleepless all night, until dawn.", "explain": "Ominous sign. Danger recently. (Rat year/day/person)."},
    111: {"poem": "Autumn frost is severe, summer sun is hot. New flowers fresh, old flowers drowned. Worldly sentiments are cold and warm, no need to speak when meeting.", "explain": "Rely on yourself. Others are unreliable."},
    112: {"poem": "Hero's ambition not unfolded, driving without fear of labor. Dare to divine good and bad, seize the prize in Northwest.", "explain": "Do not fear hardship. Choose direction carefully."},
    113: {"poem": "Sickness is deep, groggy all day. Thunder shakes, body becomes healthy and light.", "explain": "Illness hard to cure immediately. Need time and good doctor."},
    114: {"poem": "Easy not easy, hard not hard. Suddenly waves rise, laughter two or three times.", "explain": "Stuck situation. Sudden change. Problems solved."},
    115: {"poem": "Road blocked, door closed. Be cautious, clouds hide the black moon.", "explain": "Ominous."},
    116: {"poem": "Snail horn and fly head profit, now accommodated. Grass top people laugh at you, suitable to start not suitable to end.", "explain": "Greedy for small profit, cannot achieve big things. Good start bad end."},
    117: {"poem": "Pearls and jade roll in the plate, fields and gardens definitely abundant. Do not say plan not fulfilled, this trip will be prosperous.", "explain": "Effort pays off. Wait patiently."},
    118: {"poem": "Moon is bright, flowers bloom again. Matters are leisurely, nothing does not fit.", "explain": "Best state. Everything goes as wished."},
    119: {"poem": "Hazy autumn moon reflects on red door, bird sounds outside forest, distant temple monk. Noble person comes to guide, no need for clever words like orioles.", "explain": "Noble help in destiny. Be content and wait for luck."},
    120: {"poem": "Matter not wide, heart uneasy. Doubts for a long time, begin to be at peace.", "explain": "Anxious to solve but cannot. Finally will pass the difficulty."},
    121: {"poem": "False fame and position sinking for long, salary and horse sought but not true. A piece of colorful cloud comes after autumn, scenery of last year is fresh for a time.", "explain": "Busy for nothing. False fame. Luck turns after autumn/middle age."},
    122: {"poem": "Stop, stop, stop. There is end and start. Like moon like flower, just keeping achievements.", "explain": "Success and failure are destiny. Do not force it."},
    123: {"poem": "Full moon completely round, colors are joyful. Wind and clouds send off, harmony for ten thousand years.", "explain": "Great luck. Everything fulfilled. Icing on the cake."},
    124: {"poem": "Precious mirror is new, reflects two people. Knot in heart, union of same heart.", "explain": "Marriage coming or happy marriage. Partnership profitable."},
    125: {"poem": "Those below do not love those above, human hearts easily scatter. Opportunity lost by one, everything turns to ash.", "explain": "Arrogant leader, alienated followers. Failure at critical moment."},
    126: {"poem": "Dusty and waiting for time for long, who knows the quiet window. If meeting a person in purple/green to guide, wealth and fame can be expected.", "explain": "Luck not smooth. Ambition not stretched. Need a mentor."},
    127: {"poem": "Tiger crouching on the road, pedestrians do not call wildly. Be careful by the roadside, disaster naturally vanishes.", "explain": "Be careful. Otherwise disaster."},
    128: {"poem": "Harmony not harmonious, same not same. Clouds turn to rain, almost empty. Advance and retreat, beware of little merit in the end.", "explain": "Inauspicious. Career disputes. Relationship estranged. Be careful."},
    129: {"poem": "Matter in East, success in West. Scenery and moonlight are bright. Flute sound in high tower.", "explain": "Success comes unexpectedly in leisure."},
    130: {"poem": "Matter round, object circulates. One comes one goes, walking on blue sky.", "explain": "Great luck. Everything round. Wealth rolls in."},
    131: {"poem": "Wind and waves in shallow water, thorns grow on flat ground. Speech fears conflict, afraid of no aim.", "explain": "Bad luck. Careful speech causes trouble. Better be silent."},
    132: {"poem": "After autumn moon clouds open, when warm wind and rain pass. If meeting old friend from Chu, an ordinary recommendation should not be doubted.", "explain": "Smooth environment. Recommendation from old friend is good. Don't ask for too much."},
    133: {"poem": "Heart decided, why worry about the matter. Gold scales already on hook, fame and profit collected in one net.", "explain": "Auspicious. Determined heart leads to success."},
    134: {"poem": "Mind confused self not confused, matter wide heart not wide. To know the true news, still separated by two mountains.", "explain": "Cannot be optimistic yet."},
    135: {"poem": "Insufficient in laughter, sorrow and crying inside and out. Clouds scatter moon shines, turning disaster to blessing.", "explain": "Surface looks insufficient. Obstacles removed. Disaster turns to blessing."},
    136: {"poem": "Magpie chatters before the eaves, worries gone, joy natural. One person advances one retreats, good marriage in the end.", "explain": "Arranged properly. No conflict. Marriage can be united."},
    137: {"poem": "Thorns grow on flat ground, wind and waves rise from four sides. Leaning on railing looking sadly, silent towards setting sun.", "explain": "Troublesome things coming. Inner sorrow no one understands."},
    138: {"poem": "Plan decided, why worry. Moon shines on high tower, guest in clouds nods.", "explain": "Arranged. No need to worry."},
    139: {"poem": "Strange, strange, strange. Location and timing. After lamp flower sends news, movement and stillness are suitable.", "explain": "Success depends on timing and location."},
    140: {"poem": "Meet or not meet, encounter or not encounter. Moon sinks in sea bottom, person in dream.", "explain": "Everything is vague."},
    141: {"poem": "Guard against thunder in dark, suspicion is totally false. In a blink black clouds gather, sun comes out from Fusang.", "explain": "Worries are false. Truth will come out soon."},
    142: {"poem": "Benefit in war in central state, gifts in royal court. Phoenix carries decree to sun side, enjoy good name and glory everywhere.", "explain": "Merit in foreign land. Return with fame."},
    143: {"poem": "Sighing over outside worries, lamenting inside noise. Mood tangled, spirit upside down.", "explain": "Inauspicious. Public and private troubles."},
    144: {"poem": "One mountain one water, wind and waves are calm. Another sky in the pot.", "explain": "Organization has waves but safe. Family safe."},
    145: {"poem": "Don't worry about danger, why fear wind and waves. If meeting 'Grass Head' person, blue clouds road is close.", "explain": "Auspicious. Danger turns to safety. Noble person (Surname with Grass radical?)."},
    146: {"poem": "Boat oars fast in midstream, flowers bloom spring leaves again. Matter calm heart not quiet, causing many doubts.", "explain": "Confused mind. Wait for new spring. Travel caution. Marriage reef."},
    147: {"poem": "Can save and store, piece of jade inch of pearl. Steady and stable, meeting good plan ahead.", "explain": "Do not waste. Wait for good opportunity."},
    148: {"poem": "Son hurries to court early, asks about journey to blue clouds. Noble person comes to help, flowers fade seeds form.", "explain": "Teach children early. Noble help. Wish fulfilled."},
    149: {"poem": "One heart two matters, one matter two hearts. New flowers on withered tree, wait for spring.", "explain": "Mind not focused. Impatient. No success until changed."},
    150: {"poem": "Great matter hard to plan; leftover flowers no longer fresh.", "explain": "Time passed. Too old. Impossible to plan big things."},
    151: {"poem": "Do not say matter has no error, many advances and retreats in it. Moon round and missing, brightness polished more.", "explain": "Good things take grinding."},
    152: {"poem": "Do not sigh over delay, do not say it won't end. Long pole finally in hand, one fish on gold hook.", "explain": "Patience and perseverance lead to success."},
    153: {"poem": "Matter called should have taboos, not done fear stumbling first. Want to go but slow, must borrow power.", "explain": "Don't be hasty. Rely on help."},
    154: {"poem": "Foot uneasy, cart uneasy. Two things match, worry comes then joy.", "explain": "Blessing in disguise. Together brings good luck."},
    155: {"poem": "Cauldron breaks leg, cart loses spoke. There is noble person, reorganize and continue.", "explain": "Start is very unsmooth. Noble help. Reorganize."},
    156: {"poem": "Consulting words, waves boiling. Long time no harm, time is unfavorable.", "explain": "Lawsuit or contract negotiation failure. Long argument."},
    157: {"poem": "Noble guest naturally close, fame achieved easily. To get gold must accumulate virtue, look up at sun rising.", "explain": "Destined to be prominent. Accumulate virtue or lose everything."},
    158: {"poem": "Waves rise on flat ground, sought matter becomes hard daily. Jokes have taboos, same heart matters happy.", "explain": "Bad luck. Work with close friends to be safe."},
    159: {"poem": "Wild wind blows black clouds fly, moon in sky center cannot be covered. Idle time temporarily related, in the end no exploitation.", "explain": "Matter/Person is like moon, pure. Cannot be covered by black clouds."},
    160: {"poem": "Person leaning on tower, many worries. Calmly progress, matter starts without worry.", "explain": "Solitary and unhappy. Look far ahead, no worry."},
    161: {"poem": "One point touches spring, withered branches new. Ambition focused then meet, avoid two or three hearts.", "explain": "Focus leads to recognition. Promotion."},
    162: {"poem": "Road far away, door blocked. Fog covers, clouds open see sun.", "explain": "Wait for time and luck."},
    163: {"poem": "Fish on hook, line is weak. Hard to collect, use strength again.", "explain": "Opportunity/Wealth hard to hold due to insufficient strength. Try harder."},
    164: {"poem": "Guiding and pulling, diligence brings natural joy. Action has no disadvantage, sad things turn round.", "explain": "Helpful person. Good relationships. Everything goes well."},
    165: {"poem": "Doubt, doubt, doubt. One laugh then one sorrow. Fallen red flowers on ground no one sweeps, alone facing west wind with sad eyebrows.", "explain": "Don't try suspicious things. Think thrice. Avoid sorrow."},
    166: {"poem": "Top and bottom not harmonious, labor without merit. Go out to main road, protect beginning and end from there.", "explain": "Leave discordant group. Create new situation."},
    167: {"poem": "Great matter can succeed, benefit without blame. Person holding whip in clouds, report after three autumns.", "explain": "Guidance from stranger. Smooth. Success after 3 years/autumns."},
    168: {"poem": "Mulberry and elm urge evening scenery, missing moon hard to round. If meeting knife/awl guest, know joy is natural.", "explain": "Dead end. Hard to turn. Saving life is lucky."},
    169: {"poem": "Written all past and future, danger hard to go back and forth. If getting fair wind, small boat crosses distant mountains.", "explain": "Hard to get wish. Wait for heaven's time."},
    170: {"poem": "Do not sigh over leftover flowers, flowers bloom on withered tree. Spring meaning at house head, laughing happily.", "explain": "Disappointment. But turning point appears."},
    171: {"poem": "One matter totally empty, one matter becomes joy. If meeting person by mouth, heart can rely.", "explain": "Gain and loss mixed. Trust reliable person."},
    172: {"poem": "Want to get rabbit in moon, must rely on peach and plum ladder. High mountain comes to guide, double joy on eyebrows.", "explain": "Hard to get item needs extraordinary help."},
    173: {"poem": "Matter fulfilled don't worry, spring wind joy natural. Drop three foot hook, proudly catch fresh scale.", "explain": "Great luck. Wishes fulfilled. Happy events."},
    174: {"poem": "Round and missing, missing and round. Low and dense to socialize, fate seen when time comes.", "explain": "Perfection depends on luck. Everything is like this."},
    175: {"poem": "Ride sick horse, up dangerous slope. Guard against falling, see蹉跎.", "explain": "Bad luck on top of bad luck. Extremely declined."},
    176: {"poem": "Two matters already harmonious, light boat meets fair wind. Way lost person proud, singing in rapid current.", "explain": "Don't get carried away. Danger in pride."},
    177: {"poem": "White jade covered in dust, gold buried in earth. Long time brilliance, needs person to lift.", "explain": "Talent buried. Needs someone to promote."},
    178: {"poem": "Upper connection unstable, lower connection discordant. Tangled and disturbing, wind and waves on flat ground.", "explain": "Incompatible top and bottom. Endless entanglement."},
    179: {"poem": "Smiling behind back, walking in middle is best. What is sought is hopeful, no need to frown.", "explain": "Wish will come true. Why worry?"},
    180: {"poem": "Haggard no one asks, hearing cuckoo in forest. One sound of flute under mountain moon, tears flowing for a thousand miles.", "explain": "Lovers separated. Or lonely fate. Sadness."},
    181: {"poem": "Receiving deep grace in lotus fragrance, new seal when moon is full. From now fame heavy as mountains, glory straight to silk ribbon.", "explain": "Official career: Great luck. Promotion."},
    182: {"poem": "Flowers fall meeting spring, traveler halfway. Matter done but not accomplished, entangled for two or three weeks.", "explain": "Not the right time. Obstacles in next month. Wait."},
    183: {"poem": "Want to go but stop, wandering endlessly. Shaking do not force, stop if you can stop.", "explain": "Indecisive. Forced action. Better to be quiet."},
    184: {"poem": "Heart matter peaceful, socialization not yet complete. Meeting Dragon brings luck, people and moon round forever.", "explain": "Not fully resolved but safe. Dragon year/person brings luck."},
    185: {"poem": "Dreaming of mountain pass, water deep hard to fish. Fame and profit hopeful, eyes not yet smiling.", "explain": "Want to change environment but don't know how. Future opportunity, not now."},
    186: {"poem": "Three arrows open cloud road, seeking success in days. Many idle words, turned into laughter and song.", "explain": "Good luck. Especially for business/entrepreneurship."},
    187: {"poem": "Do not be attached, mistake future. End in noise, leave the house.", "explain": "Don't cling to person/place and miss big things. Leave early."},
    188: {"poem": "Ten thousand miles waves calm, one day wind and moon idle. No obstacle to fame and profit, walking out of heavy passes.", "explain": "Great luck."},
    189: {"poem": "Craving plums, painting cakes. Wasting heart, like catching shadows. Meet Tiger and Dragon, then can wake up.", "explain": "Fantasy habit. Change it."},
    190: {"poem": "Matter confused heart not confused, matter wide heart not wide. A happy gathering, soon out of heavy passes.", "explain": "Alone is hard. With help, success is hopeful."},
    191: {"poem": "No boat at midnight crossing, waves fear hitting sky. Moon slanting clouds pale, someone sends news.", "explain": "Don't be rash. Act when conditions are ready."},
    192: {"poem": "Matter if detained, person does not stand out. Traffic blocked, want to see nothing.", "explain": "Be cautious and alert."},
}

# Add Part 2 (193-384) in next block to avoid variable size issues? 
# Actually I'll merge them in the script.
