
import os
import json

en_data_2 = {
    193: {"poem": "Ten thousand miles sail turns, waves calm not startled. Walking without obstruction, distance connects to ferry.", "explain": "Everything steady and smooth. Expansion is sure to win."},
    194: {"poem": "Body experienced stormy waves, East wind is good. Retire in peace, currently still early.", "explain": "Good for retirement. For others, dangerous but safe. Hard to withdraw now."},
    195: {"poem": "Crane comes out of clouds, person returns under moon. New joy on face, no need to frown.", "explain": "Auspicious. Nothing unfavorable."},
    196: {"poem": "Fish in deep pool can be fished, bird in deep valley can be netted. Just use long-term heart, no need to doubt.", "explain": "Patience leads to success. Do not doubt."},
    197: {"poem": "Advance uneasy, retreat impossible. Up and down follow, a bright pearl.", "explain": "Dilemma. Needs unity of everyone to succeed."},
    198: {"poem": "Taking the initiative, road not lost. Currently not satisfactory, barely avoid right and wrong.", "explain": "Used to be smooth, now not. But trouble avoided."},
    199: {"poem": "Sparrows chatter on high branch, traveler at old ferry. Halfway unfinished matter, sunset brings sorrow.", "explain": "Conflicting opinions. Halfway done creates future sorrow."},
    200: {"poem": "Chisel stone get jade, wash sand get pearl. Right now before eyes, why hesitate.", "explain": "Great luck. Unexpected harvest in everything."},
    201: {"poem": "Wind and rain urge spring to leave, peach and plum flowers fall. Someone singing and laughing by the peach, knowing your heart is messy.", "explain": "Good times don't last. Beware of villains gloating."},
    202: {"poem": "Spring in fairyland for a time, flowers and willows new in courtyard. Good news spreads, plants are joyful.", "explain": "Auspicious."},
    203: {"poem": "Matters overlap outside door, women meet often. Although wise woman helps, vaguely hard to harmonize.", "explain": "Villains in power. Outsider in charge. Hard to succeed even with help."},
    204: {"poem": "Joy in matter, light on face. Good to discuss start and end. Days and months long in the pot.", "explain": "Get a virtuous wife. Family harmony. Pregnancy."},
    205: {"poem": "Dark goes and light comes, worried matter can be harmonized. End in a smile, do not guess now.", "explain": "Fate determines dark and light. Don't worry."},
    206: {"poem": "Precious mirror no dust, gold mink cut. Heaven's will matches, never attract dust.", "explain": "Double happiness. Upright and noble. Favored by heaven."},
    207: {"poem": "Harmonious matter, success in talking and laughing. Good news halfway, stepping on blue clouds.", "explain": "Marriage set in laughter. Promotion news on the way. Double joy."},
    208: {"poem": "Flower faded moon missing, mirror broken hairpin divided. Stop coming and going, matter starts to be peaceful.", "explain": "Very ominous. Divorce likely. Stop everything."},
    209: {"poem": "Good news comes outside door, career should have celebration. Fame and profit change, goose row finally breaks formation.", "explain": "Good start. Success. But brothers/partners may separate or be damaged."},
    210: {"poem": "Ten thousand miles good landscape, wind and sand all day. Bait swallowed on hook, why meet waves.", "explain": "Sudden change destroys near success."},
    211: {"poem": "Double swallows carry letter and dance, coming together soon. Lonely guest staying, get off fishing platform from now.", "explain": "Expected person/matter coming soon."},
    212: {"poem": "Looking at several mountains, high and deep gradually climbable. Look up at sky, bright moon in human world.", "explain": "Mysterious things will be clear. Don't fear."},
    213: {"poem": "Use it then act, discard it then hide. One rider out of heavy pass, good news nearby.", "explain": "Use ambitious and capable people. Success soon."},
    214: {"poem": "Accumulate virtue and merit for descendants. Sacrifice to gods and neighbors. Fame fulfilled day, look back landscape new.", "explain": "Do good deeds. Good rewards."},
    215: {"poem": "Safe road flat and smooth, one goose flies in clouds. Peach blossom meets sudden rain, woman cries by water.", "explain": "Bad for love/marriage. Twists in other matters."},
    216: {"poem": "War inside door, relatives and enemies not harmonious. Red robe approaches sun and moon, start to laugh.", "explain": "Family discord. Be careful. Success in the end."},
    217: {"poem": "There is a person, gets a deer. Matter round, rope outside door.", "explain": "Success but beware of trouble. Wealth divided, partner entangled."},
    218: {"poem": "You go no benefit, flowers bloom and reach autumn. Severe frost comes, retreat does not stay.", "explain": "Ominous."},
    219: {"poem": "New moon as hook, clear wind as line. Lift net in misty waves, brocade scales easy to see.", "explain": "Good. Handy and successful."},
    220: {"poem": "Lock first, continue to guard. Small details not cautioned, follow to big disaster.", "explain": "Small mistake leads to big disaster. Prevention is key."},
    221: {"poem": "Swallows talk and orioles sing, flowers fill the courtyard. Leaning on railing spring sleep, speechless removing sorrow.", "explain": "Luck turned. Everything smooth."},
    222: {"poem": "Labor heart, labor heart, labor heart has success. Clear wind borrows power, laughing at future.", "explain": "Be attentive and thoughtful. Future is bright."},
    223: {"poem": "Progress and hesitate, spring wind blows willow catkins. Traveler tired by water, worry by pillow.", "explain": "Gradual progress. Obstacles when near success."},
    224: {"poem": "Jade and stone still obscure, how can bear small regrets. End no blame, laughing.", "explain": "Confused but small mistakes. No big harm."},
    225: {"poem": "Drooping wings go to distant sky, all because of escaping disaster. A way of economy, again full garden spring.", "explain": "Escape disaster. Return to comfort after struggle."},
    226: {"poem": "Good news arrives, open smiling face. Fly away once, push clouds to sky.", "explain": "Great luck. Promotion. Success."},
    227: {"poem": "Green felt empty keeping old, nest on branch generates wind. Do not be happy for a moment, suspect this image is ominous.", "explain": "Inauspicious. Danger remains. Precarious."},
    228: {"poem": "Do not say thorns are evil, finally roost for phoenix. Wait for now, why hesitate early.", "explain": "Obstacles but happy ending. Patience needed."},
    229: {"poem": "Up and down harmonious, sorrow resolved. Thousand peaks clouds, one wheel moon.", "explain": "Family harmony brings prosperity."},
    230: {"poem": "Jade out of Kunlun stone, boat leaves old ferry beach. Action and hiding hopeful, using and discarding not hard.", "explain": "Truth revealed. Decision easy."},
    231: {"poem": "Mind hard to stretch now, guest comes slowly. Gold cart experienced danger, stingy has end.", "explain": "Tangled mind. Delay. Regret later."},
    232: {"poem": "Can send, can entrust. Matter slow, no error.", "explain": "Can entrust others. Slow but safe."},
    233: {"poem": "Fear and worry, all before eyes. If meeting clear mirror, point out empty transmission.", "explain": "Deep worry. Need guidance to solve."},
    234: {"poem": "Moon hidden in clouds, lost way. Clouds scatter moon bright, gradually suitable to progress.", "explain": "Obstacle temporary. Progress after clearing."},
    235: {"poem": "Road crazy calling, no wind and waves. Time bad mind messy, rely on noble help.", "explain": "Conditions good but luck bad. Rely on help."},
    236: {"poem": "Cast hook in deep pool, clear cut dust. Giant turtle obtained, no need to guess.", "explain": "Take risk for wealth. Be patient."},
    237: {"poem": "Should be straight in nothing, heart matter becomes sorrow. Clouds scatter moon round again, thousand miles wind sail fast.", "explain": "Average. Clouds scatter moon shines."},
    238: {"poem": "Creation comes naturally, teacher conquers thousand miles blessing. Fame achieved with divine help, snake and rabbit meeting surely change.", "explain": "Great luck. Snake/Rabbit factors bring change."},
    239: {"poem": "Rely on divine power, demons destroyed. Destroyed and need power again. Remember firmly, avoid falling later.", "explain": "Control external help. Don't be bound by it."},
    240: {"poem": "Dao must have firm heart, firm heart completes Dao. Establish merit, return early. Build hut, cultivate true body. Fly up one day, name in immortal class.", "explain": "Cultivate self. Don't be greedy for power."},
    241: {"poem": "One thought heaven, one thought hell. Hell heaven, separate glory and shame. Self thought must be true, do not follow others.", "explain": "Thought determines fate. Don't follow crowd."},
    242: {"poem": "Sheep escapes flock, day faces people. Meet cow mouth, then bite people. One ruler one minister, ruler and minister startled. Must rely on true god to save people.", "explain": "Vague. Try again."},
    243: {"poem": "If destined person, one finger turns head. Stubborn person, repeatedly guided not leaving.", "explain": "Turn back from wrong path. Depends on fate."},
    244: {"poem": "Moon rises east, clear light can be scooped. Ten thousand miles no clouds, sea and sky blue.", "explain": "Good luck coming. Shine brightly."},
    245: {"poem": "If man gets seal of nobility, not fail world trip. Success and retire, smoke and clouds proud. Take off purple robe, that is man's way.", "explain": "Retire after success."},
    246: {"poem": "Heart moon fox, confuses world. People do not check, destroy body after long time.", "explain": "Beware of bad habits/addictions."},
    247: {"poem": "Suddenly wild wind rises, big trees lifted. Branches and leaves not withered, cultivation finally safe.", "explain": "Shock but safe."},
    248: {"poem": "Sun calendar prosperous, method needs searching. Surround four sides, charge camp against enemy.", "explain": "Don't be deceived. Investigate truth."},
    249: {"poem": "Glory and wither fixed early don't sigh. Hard work in foreign land enjoy home. Making wedding dress for others, you taste today, others taste another year.", "explain": "Fate fixed. Bad luck now. Working for others."},
    250: {"poem": "Daughter grows up, joy at door. Marry good husband, add children. Worship together, feel royal grace.", "explain": "Auspicious. Marriage/Family good."},
    251: {"poem": "Wood generates fire, mouth not shut. Madness symptom, cold and heat invade.", "explain": "Very unfavorable. Watch speech. Illness/Disaster."},
    252: {"poem": "Stop, stop, stop. Passed three years and six weeks. Not reflected, disaster on head.", "explain": "No changes for 3.5 years. Reflect to avoid disaster."},
    253: {"poem": "Fence catches fire, livestock suffers. Prevention effective, extinguishing fire becomes health.", "explain": "Prevention is key."},
    254: {"poem": "Wish fulfilled, ambition stretched. Grasp three mountains, frequently settle peace.", "explain": "Be cautious after success."},
    255: {"poem": "Lucky star shines, cassia fragrance smelled. Sky full of stars, light dazzles people.", "explain": "Great luck. Divine protection. Autumn/August noble help."},
    256: {"poem": "East South North will become ruins, Yan Ji land people not saved. If want to exert ambition, where is water source?", "explain": "Dangerous environment. Find survival resource first."},
    257: {"poem": "Death has day, life has time. Why hesitate slow. Float away, no doubt in heart.", "explain": "Destiny fixed. Don't be calculating."},
    258: {"poem": "Walking in remote place, suddenly startled. If wolves block way, kill them to be happy.", "explain": "Sudden danger. Courage needed to solve."},
    259: {"poem": "Eight gates divide eight positions, nine stars layout nine directions. Green red yellow white black, five colors roll brocade. Confrontation, two equal.", "explain": "Equal strength."},
    260: {"poem": "Lifelong not learning up, living in vain. Reincarnation unavoidable, fall into deep pit forever.", "explain": "Don't live in confusion."},
    261: {"poem": "Two children, walking together. Yin and Yang harmonious, planning happy.", "explain": "Get son and daughter (or twins). Harmony."},
    262: {"poem": "Mystery in it, revealed when rooster crows. Suddenly realize Zen gate, break ruler's door road.", "explain": "Mystery solved soon (Rooster time/year?)."},
    263: {"poem": "Several goldfish swallow bait, fishing rod turned back. Home food disliked as expensive, roam five lakes and four seas.", "explain": "Windfall might be burden."},
    264: {"poem": "Rabbit sun comes out of forest, noon time blessing arrives. Rabbit born in Tiger, see heaven's heart.", "explain": "Follow natural order."},
    265: {"poem": "No decision at noon, clear when day arrives. A good matter, six ears complete together.", "explain": "Wait a few days. Three people cooperation."},
    266: {"poem": "Lone star is demon star, ape and tree spirit. Meet this star in mountain, confuse nature and heart.", "explain": "Loneliness makes one easily confused."},
    267: {"poem": "Drip sound urges rooster crow, hurry travelers released in group. Late crossing pass, future boundless.", "explain": "Go all out. Success."},
    268: {"poem": "Person outside world, long lack of news. Family looks often, grass and trees smooth heart.", "explain": "Miss distant person."},
    269: {"poem": "Under this tree, a hole formed. If move this earth, fortune and salary gather.", "explain": "Good fortune increases even in bad place."},
    270: {"poem": "Plowing in fields, shape and spirit seem tired. No restraint, joy is great.", "explain": "Self-reliant. Tired but happy."},
    271: {"poem": "Disaster comes see ghost, ghost sickness entangles. Gold sheep finds way, body escapes disaster.", "explain": "Disaster. 'Gold/Sheep' saves."},
    272: {"poem": "Hurry up, hurry up, future go, form alliance. One hand holds sky pillar, name in history.", "explain": "Sudden mission. Alliance. Success."},
    273: {"poem": "Deep mountain has fierce tiger, tiger roars out of den. Spread might, why fear many people.", "explain": "Majestic and brave. Conquer crowd."},
    274: {"poem": "Three heavenly gates, four earthly doors. Formation set, bright road gathered. Army runs together, drum sound progress.", "explain": "Plan first then win."},
    275: {"poem": "Mountain, mountain, mountain. Build hut on mountain. Not like human building, but like clouds in sky.", "explain": "Contentment."},
    276: {"poem": "Come and go no fixed place, settle when time comes. Trek without worry, honor and disgrace not counted.", "explain": "Life of wandering. Safe journey."},
    277: {"poem": "Have son grow, become water bureau. Time meets fire reverses fortune. No need to worry, human heart bitter insufficient.", "explain": "Life not perfect. Don't worry."},
    278: {"poem": "In dark night, do not go forward. If encounter, panic. Remember firmly, must form party.", "explain": "Don't go to strange places alone. Group up."},
    279: {"poem": "Hibernating dragon out of world, head and horn generated. Clouds rise rain favors, save the people.", "explain": "Great luck. Break deadlock. Smooth path."},
    280: {"poem": "Fire smoke touches sky, sky edge all red. Meet water source, almost achieve pattern.", "explain": "Disaster uncontrollable. Need countermeasure."},
    281: {"poem": "Great road to South, ride horse to Hangzhou. Don't know Wu song, but have a soulmate.", "explain": "South is good. Find soulmate."},
    282: {"poem": "Have one acre of field, cultivate it fully. Endless harvest, all in autumn success.", "explain": "Manage what you have. Don't leave."},
    283: {"poem": "Don't dislike son no lips, fast feet cannot catch. Put in ape hole, where to find running dog.", "explain": "Hard to understand. Everyone has pros/cons."},
    284: {"poem": "Six cows plow land, open up boundless. Harvest fruit, full granary.", "explain": "No pain no gain."},
    285: {"poem": "Great ambition to sky, do not linger home. Seven eight leave early, show might in battlefield.", "explain": "Ambition in four directions. Seize time (7/8)."},
    286: {"poem": "Sunflower faces sun, loyal heart. Open wide mansion, enjoy peace.", "explain": "Loved by subordinates. Career expands."},
    287: {"poem": "People don't know immortal, no true formula. Once enter mystery gate, interesting and beneficial.", "explain": "Explore principle. Success."},
    288: {"poem": "Don't say words too deep, mud won't become true. Realize thousand mysteries, know immortal way most divine.", "explain": "Look for inner meaning."},
    289: {"poem": "Fame although practical, how about cultivating truth. True body immortal, eternal spring.", "explain": "Cultivate self better than fame."},
    290: {"poem": "Walk, walk, walk, meet a dog. Urgent search, can last long.", "explain": "Don't ignore details. Watch out for sudden events."},
    291: {"poem": "Unknown true news, news comes suddenly. Moon round moon missing night, do not open door.", "explain": "Don't trust sudden news. Ignore changes."},
    292: {"poem": "Fire prosperous not tired, water deep not dull. Consider at end, don't provoke disaster.", "explain": "Think carefully at critical moment."},
    293: {"poem": "Guest wild goose, lake land becomes land. Build merit return early. Greed not blessing, don't let chickens and ducks fight.", "explain": "Quit while ahead."},
    294: {"poem": "Wind in sky, moon at edge. Moon white wind clear, two equal.", "explain": "Good luck. Equal match."},
    295: {"poem": "Leaf returns to root, stands in heaven and earth. Water clear source long flow river sea. Person gets golden elixir long life.", "explain": "Follow nature. Long life."},
    296: {"poem": "Ride horse to Chang'an, see flowers blooming. One day rain comes, fragrance and color fade.", "explain": "Good times don't last. Prepare for rainy day."},
    297: {"poem": "Wood grows spring sky root trunk old, fruit three autumns branch leaves withered. Not withered not faded, root not seen firm.", "explain": "Stronger after setbacks."},
    298: {"poem": "Call path call path, sky will be bright. Why not stretch head and eyebrows, instead be weeds till old.", "explain": "Work hard timely. Don't procrastinate."},
    299: {"poem": "Medicine is true, take it peace. After three doses, clear enough. God in god, clear in clear. Hold tight, can live long.", "explain": "Truth stands test."},
    300: {"poem": "Three days formed society, four seas know name. Ride fast horse, straight into heaven.", "explain": "Great luck. Famous."},
    301: {"poem": "Idle at master's place, accidentally meet a person. Child face white hair, laughter generates spring.", "explain": "Noble help."},
    302: {"poem": "Idle cloud wild crane look east, only villager is soulmate. Manage layout two three springs, lights connected, bright future.", "explain": "Success after 2-3 years of management."},
    303: {"poem": "Han water ruthless, Shu water clear. Yellow river rolling, smoke and dust everywhere.", "explain": "Stay clean in chaotic world."},
    304: {"poem": "Hidden dragon trapped, not see clouds rise. Wait for clouds gather, fly to heaven.", "explain": "Wait for time."},
    305: {"poem": "Taste strong here, strong beauty not durable. How about talking and laughing, better run east and west.", "explain": "Good situation not lasting. Plan elsewhere."},
    306: {"poem": "There is villain here, do not stay. Busy pack, good to go. Days and months pass don't keep long.", "explain": "Avoid villain. Leave."},
    307: {"poem": "Dragon grows head horn, rain falls. Six seven eight early, good to save people.", "explain": "Dragon year help. Dates 6/7/8 good."},
    308: {"poem": "Venus appears Southwest, Dragon Snake compete. Dragon flies to sky, Snake killed.", "explain": "Good and evil have rewards."},
    309: {"poem": "Planted tree, wait for spring. East wind blows, flowers open on street.", "explain": "Wait for time and help."},
    310: {"poem": "Forty years bitter deep, now you enjoy time. Don't discuss, love and joy many. Cherish youth.", "explain": "Be content. Enjoy life."},
    311: {"poem": "Three winters enough, arts refined. At the end, becomes ice. Hurry turn back, don't mistake future.", "explain": "Wrong method. Change course."},
    312: {"poem": "Strange, strange. Came before, come again now. Be cautious, don't be ruined.", "explain": "Strange situation. Beware."},
    313: {"poem": "Plowing cow lying, open territory. Sit and watch harvest, millet and rice.", "explain": "Gain without pain."},
    314: {"poem": "Waist wears sword, step into golden hall. Protect three mountains, tempered hundred times.", "explain": "Outstanding success. Top of industry."},
    315: {"poem": "Young bird flies high, out of valley to tall tree. Dragon god teeth claw, change island.", "explain": "Inexperienced person suffers in society."},
    316: {"poem": "Lucky, lucky, lucky, ordinary like moon before window. Ominous, ominous, ominous, with plum blossom different. Smile to east wind, human feeling not like old times.", "explain": "Bad luck coming. Cold human feelings."},
    317: {"poem": "Fire very hot, water suitable to help. Precious ding elixir formed, lift sky reveal earth.", "explain": "Disaster has cure. Intentional trouble hard to fix."},
    318: {"poem": "Iron chain one strip, not tied lone boat. Gold knife once, head falls early.", "explain": "Cut the knot quickly."},
    319: {"poem": "In twelve hours, urgently refine. One moment delay, no place to put foot.", "explain": "Go all out. No delay."},
    320: {"poem": "Wind rises Southwest, red sun in sky. Mysterious formula, one palm can hold.", "explain": "Mystery solved when time comes."},
    321: {"poem": "Silence everywhere, moon in sky. Suddenly covered by clouds, brightness becomes hazy.", "explain": "Maintain image. Beware of slander/plot."},
    322: {"poem": "A soulmate, waiting at horizon. Do not delay, reflect in quiet night.", "explain": "Too highbrow. Adjust self."},
    323: {"poem": "Dogs gather, grind teeth. Shake head wag tail, just looking after house.", "explain": "Don't be deceived by villains gathering."},
    324: {"poem": "Wife front husband back walk together, omen clear. If you have affection remember, ten years grace don't forget.", "explain": "Wife stronger than husband. Cherish grace."},
    325: {"poem": "Rat hides in hole, naturally peaceful. Once head shown, cat follows. Spread might extend claw, rat loses life.", "explain": "Stay quiet. Keep secret."},
    326: {"poem": "Book has woman face like jade, book has golden house. Read five carts of books, ambition satisfied. Why worry and busy.", "explain": "Study hard. Don't worry."},
    327: {"poem": "Leopard changes to pattern, ride dragon luck comes. Naked becomes rich, everything renewed.", "explain": "Get good son-in-law. Life changes. Wealth."},
    328: {"poem": "Lone Yang weak, group Yin overflow. Strength exhausted, cannot be old. True caution, can be preserved.", "explain": "Evil grows. Caution preserves."},
    329: {"poem": "Morning rain clears reflects green creek, heavy spring colors on door. Gold endless family rich, why envy brocade clothes?", "explain": "Rich family. Be content."},
    330: {"poem": "World has many thorns, human feelings sigh. Profit and fame if have road, diligent pursuit of career.", "explain": "Don't fight. Be diligent and content."},
    331: {"poem": "Mountain ends road turns lost, water fast boat hard to cross. Don't force everything, encounter jealousy.", "explain": "Travel unfavorable. Forcing brings trouble."},
    332: {"poem": "Time has many hardships, trembling. Cautious and fearful, walking on thin ice. Must know future danger, one lantern in wind.", "explain": "Bad luck. Danger ahead. Be cautious."},
    333: {"poem": "One flower branch beautiful and fragrant, fragrance penetrates room. Season wind blows finally smile, good sentences before feast.", "explain": "Woman beautiful/wise. Man noble."},
    334: {"poem": "Since holding firmly, merit before others. Special joy, follow dragon to heaven.", "explain": "Perseverance leads to success."},
    335: {"poem": "Far travel waves one leaf boat, now pass beach head. Years of heart matter achieved, counting past many worries.", "explain": "Great luck. Smooth. Wishes fulfilled."},
    336: {"poem": "Receive ruler's salary, long auspiciousness. Full not overturned, keep it prosperity. No laziness no pride, eternal health.", "explain": "Don't be proud or lazy to keep success."},
    337: {"poem": "Everything not by human calculation, life is arranged by fate. Don't suspect, fate has it eventually. Why busy in dust, rest!", "explain": "Fate decides. Don't be greedy."},
    338: {"poem": "Piece of worry not willing to stop, flower meets spring rain beauty hard to keep. Proud return, disappointed return, immortal only this one plan.", "explain": "Unsmooth. Worried. Love change."},
    339: {"poem": "Two women one husband, up and down drive away. Yin energy rides Yang, use is waste.", "explain": "Beware of lust. Waste."},
    340: {"poem": "Double swallows return to South, seek Wang Xie family. Hall spring quiet, enter here to trust life.", "explain": "Return to changed scene."},
    341: {"poem": "Fate difficult time against, disaster comes body tired. Look at heaven not care, sigh parents sick dangerous.", "explain": "Inauspicious. Everything unfavorable."},
    342: {"poem": "Picking herbs Tiantai road lost, peach blossom flowing water beautiful time. Spring wind bird calls sentimental, tell Liu Lang not to return.", "explain": "Meet soulmate in foreign land. Don't return yet."},
    343: {"poem": "Out of warm into cold, quilt thin clothes single. Leave my compassion boat, hard to solve crime.", "explain": "Bad luck and own fault. Seek faith."},
    344: {"poem": "Three sheng three dan put in one dou, full and overflow, you get it.", "explain": "Don't force fit. Fullness invites loss."},
    345: {"poem": "Who says hometown has no taste, drifting lakes and seas at horizon. Let sigh, Mid-Autumn moon hidden spring rain wets flower, many travelers miss home.", "explain": "Wandering outside. Lonely. Miss home."},
    346: {"poem": "Clouds scatter moon in sky, meet before cow after horse. Draw bow to resist, one arrow settles success.", "explain": "Rat/Goat year success."},
    347: {"poem": "Horse advances slow seems to have journey, moon sinks west sea sun rises east. Luck comes why labor, wind sends river lake ten thousand miles clear.", "explain": "Luck turning good. Situation changes."},
    348: {"poem": "Clouds across mountain water vast, thousand miles looking at hometown. Disaster comes don't hate, leaning on door sad in setting sun.", "explain": "Hardship. Sadness."},
    349: {"poem": "Wind and waves now calmed, boat meets safe flow. From now fame achieved, why sigh white hair.", "explain": "Trouble over. Smooth journey. Success."},
    350: {"poem": "Arrive at safe place, landscape ten thousand miles. Green willow fragrant grass, wind fast horse hoof light.", "explain": "Hardship over. Enter good state."},
    351: {"poem": "Eagle in autumn momentum turns strong, ride wind spread wings to moon palace. Glory if ask future, fame reaches nine heavens.", "explain": "Luck turns. Powerful momentum. Success."},
    352: {"poem": "Rat causes trouble all night not peaceful, cat calls a few nights peace. People do not know like beast, reason very clear.", "explain": "Villain rampant but short-lived."},
    353: {"poem": "Two people at side, sun above. Shine on your inch heart, immortal machine ever clear.", "explain": "Gods watching. Don't cheat. Truth reveals."},
    354: {"poem": "Gentleman way fades, villain way grows. Yin energy gloomy, Yang energy not raised. How how, good merchant hides deep.", "explain": "Hide talent. Don't show off."},
    355: {"poem": "Go to Chang'an, Northeast corner. Meet Heavenly Gate, then have whereabouts.", "explain": "Unknown. Depends on question."},
    356: {"poem": "Slowly enter Tiantai, listen to good news. Picking herbs has fairy boy, cave lists spring colors.", "explain": "Actively search. Will find."},
    357: {"poem": "Thinking all night, better do it. If wrong, worry lungs and liver.", "explain": "Action better than thinking."},
    358: {"poem": "Heart fine daring coarse, can win general's duty. Brave forward success failure not in mind, chest hold steady, enemy naturally trapped.", "explain": "Brave and steady wins."},
    359: {"poem": "Heaven pities ascetic, finally not fall into red dust. Clear heart can see Dao, disturbing loses true spirit.", "explain": "Focus brings success."},
    360: {"poem": "Catch rhino in abyss, seek fish in mountain. From morning to evening, merit negative strength donated. Change string change track, maybe can keep whole.", "explain": "Wrong direction. Change method."},
    361: {"poem": "Hand holding a wooden fish, beg along street. Not see Xu Gong come, but meet a bird go.", "explain": "Vain effort."},
    362: {"poem": "Water fire completed, Yin Yang match. Nurture things new people, participate heaven praise earth.", "explain": "Conflict resolved. Harmony. Suitable for all."},
    363: {"poem": "Ride jade rabbit, to Guanghan. Meet Chang'e, climb cassia. Full body fragrant, two sleeves scent.", "explain": "Great luck. Noble help. Rise high. Marriage good."},
    364: {"poem": "A god, follow you. Preach to people, show spirit everywhere.", "explain": "Capable. Smooth social skills. God-like."},
    365: {"poem": "Fire in furnace, gold in sand. Effort arrived, elixir formed.", "explain": "Effort leads to success."},
    366: {"poem": "This trip ten thousand miles, but meet soulmate. Same heart help, establish great name.", "explain": "Far travel. Meet soulmate. Success."},
    367: {"poem": "Seeking fragrance spring day, just see flowers bloom. Every flower can be picked, every branch can be planted.", "explain": "Right time. Success everywhere."},
    368: {"poem": "Dragon chants, clouds rise. Rush to sky, see peace. Literary and martial, ruler and minister.", "explain": "Auspicious sign. Harmony."},
    369: {"poem": "Tiger on gold list, bravery what use. How like mountain old man, not rich still interesting.", "explain": "Abnormal situation. Seek expert help."},
    370: {"poem": "Pass sheep intestine, enter thoroughfare. Five tombs fur coat horse, think of hometown.", "explain": "Hardship to comfort. Don't forget roots."},
    371: {"poem": "Fire conquered by water, fire extinguishes light. Water potential surging, source far flow long.", "explain": "Emergency needs caution. Beware of future."},
    372: {"poem": "East pavilion feast open, good guests come. Singing together, express feelings.", "explain": "Famous. Social. High class."},
    373: {"poem": "World seems clear peaceful, unknown resignation stopped. Pack carefully, beware of fire.", "explain": "Nothing wrong but self-trouble. Or beware fire."},
    374: {"poem": "Jump dragon gate, must excite waves. Thunder and lightning boom, jump ten thousand feet.", "explain": "High goal needs super ability and chance."},
    375: {"poem": "Mountain has ancient pine, standing tall to sky. Trunk old branch longer, heaven and earth life long.", "explain": "Follow nature. Seize chance."},
    376: {"poem": "Slander words, don't argue. In the end, number fixed. Busy life, better be content.", "explain": "Ignore slander. Fate fixed. Be content."},
    377: {"poem": "A pig, can sacrifice to heaven and earth. Although lose life, considered benefit.", "explain": "Useful sacrifice."},
    378: {"poem": "Rather than busy day, better think night. Labor body day, quiet night.", "explain": "Work hard day, rest night. Clear meaning."},
    379: {"poem": "East wind comes, flowers open. Everyone cheers, drink three cups.", "explain": "Ready. Happy event."},
    380: {"poem": "Coarse food drink water, joy in it. Rich food, makes heart dim.", "explain": "Contentment."},
    381: {"poem": "Yellow ox opens earth, great effort opens territory. West success time, grain fills granary.", "explain": "No pain no gain."},
    382: {"poem": "Snake can turn to dragon, head horn coming out. Thunder on flat ground, show dragon snake power.", "explain": "Ordinary to extraordinary. Success."},
    383: {"poem": "Jiuhua mountain top, purple energy rising. Different boat, take to go forward.", "explain": "Opportunity to succeed. Smooth."},
    384: {"poem": "People are not sages, few can be without fault. Fault changed is no fault. Flowers not enough proof, fruit is standard. Open embrace happy.", "explain": "Admit and correct mistakes. Result matters. Be open."},
}

file_path = "zhuge_data.json"
if os.path.exists(file_path):
    with open(file_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    # Merge en_data_1 and en_data_2
    # Assuming en_data_1 is defined in previous block or we merge here if we run sequentially
    # But since this is a separate write, I need to make sure en_data_1 is available or I read the file again?
    # I will assume I am appending to the file created in previous step.
    # So I will write the en_data_2 definition and the update logic.
    pass 
else:
    data = []

# Update Logic (to be appended to the script)
